name: Merge
on:
  push:
    branches: [main]
jobs:
  ci:
    uses: Novolis-Platform/novolis-workflows/.github/workflows/dotnet-merge.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
